name: Call Reusable Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  call-code-check:
    uses: ./.github/workflows/code-check.yaml
    with:
      python-version: '3.10'
  call-ci:
    needs: call-code-check
    uses: ./.github/workflows/unittest.yaml
    with:
      python-version: '3.10'

  release-page:
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    needs: call-code-check
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
