name: Run Pytest

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        description: 'Python version to use'
        required: false
        default: '3.10'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
          poetry add pytest
      - name: Run pytest
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          poetry run pytest tests/
